// <auto-generated />
using DwarfColony.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DwarfColony.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DwarfColony.Models.Entities.BaseResources.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Charcoal")
                        .HasColumnType("int");

                    b.Property<int>("Coal")
                        .HasColumnType("int");

                    b.Property<int>("Food")
                        .HasColumnType("int");

                    b.Property<int>("GoldOre")
                        .HasColumnType("int");

                    b.Property<int>("IronOre")
                        .HasColumnType("int");

                    b.Property<int>("RawFood")
                        .HasColumnType("int");

                    b.Property<int>("Stone")
                        .HasColumnType("int");

                    b.Property<int>("Water")
                        .HasColumnType("int");

                    b.Property<int>("Wood")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.Dwarfs.Dwarf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionRemainingTime")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CurrentAreaId")
                        .HasColumnType("int");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<int>("Hunger")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<int>("Job")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetAreaId")
                        .HasColumnType("int");

                    b.Property<int>("Thirst")
                        .HasColumnType("int");

                    b.Property<int>("TravelRemainingTicks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAreaId");

                    b.HasIndex("TargetAreaId");

                    b.ToTable("Dwarves");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.World.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanRest")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistanceFromBase")
                        .HasColumnType("int");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<int>("MaxWorkers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.World.AreaResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("AreaResources");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.WorldResources.RareResources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<double>("ChanceToMine")
                        .HasColumnType("float");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("RareResources");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.WorldResources.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.Dwarfs.Dwarf", b =>
                {
                    b.HasOne("DwarfColony.Models.Entities.World.Area", "CurrentArea")
                        .WithMany("CurrentDwarves")
                        .HasForeignKey("CurrentAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DwarfColony.Models.Entities.World.Area", "TargetArea")
                        .WithMany("IncomingDwarves")
                        .HasForeignKey("TargetAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentArea");

                    b.Navigation("TargetArea");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.World.AreaResource", b =>
                {
                    b.HasOne("DwarfColony.Models.Entities.World.Area", "Area")
                        .WithMany("Resources")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DwarfColony.Models.Entities.WorldResources.ResourceType", "ResourceType")
                        .WithMany("AreaResources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.WorldResources.RareResources", b =>
                {
                    b.HasOne("DwarfColony.Models.Entities.World.Area", "Area")
                        .WithMany("RareResources")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DwarfColony.Models.Entities.WorldResources.ResourceType", "ResourceType")
                        .WithMany("RareResources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.World.Area", b =>
                {
                    b.Navigation("CurrentDwarves");

                    b.Navigation("IncomingDwarves");

                    b.Navigation("RareResources");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("DwarfColony.Models.Entities.WorldResources.ResourceType", b =>
                {
                    b.Navigation("AreaResources");

                    b.Navigation("RareResources");
                });
#pragma warning restore 612, 618
        }
    }
}
